### ISSUE TITLE
Calendar is stuck loading

### ISSUE THREAD

**Issue by duncanleo** [alphatrl/classmaid#98]
<img width="547" alt="image" src="https://github.com/foldaway/smu-shortcuts/assets/7417870/5f2ef673-63d5-49f1-bfde-dde2a0289a4a">

**Comment by alphatrl** [comment]
Issue is caused by an invalid date calculation for SMU in the `school-semesters` repo 

https://github.com/foldaway/school-semesters/issues/11

**Comment by alphatrl** [comment]
Fixed in https://github.com/foldaway/school-semesters/pull/14
